# Generated by Django 3.2.5 on 2024-04-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('fee', models.IntegerField()),
                ('username', models.TextField(max_length=30)),
                ('contact', models.IntegerField()),
                ('date', models.DateField()),
                ('hname', models.TextField(max_length=250)),
                ('ctime', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('qualification', models.TextField(max_length=30)),
                ('department', models.TextField(max_length=30)),
                ('hname', models.TextField(max_length=30)),
                ('experience', models.TextField(max_length=30)),
                ('ctime', models.TextField(max_length=30)),
                ('place', models.TextField(max_length=30)),
                ('fee', models.IntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('contact', models.IntegerField()),
                ('mail', models.EmailField(max_length=30)),
                ('message', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pregnancies', models.TextField(max_length=30)),
                ('Glucose', models.TextField(max_length=30)),
                ('Bloodpressure', models.TextField(max_length=30)),
                ('Skinthickness', models.TextField(max_length=30)),
                ('Insulin', models.TextField(max_length=30)),
                ('BMI', models.TextField(max_length=30)),
                ('Diabetespedigreefunction', models.TextField(max_length=30)),
                ('Age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('mail', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
