# Generated by Django 3.2.5 on 2024-04-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='gender',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
