# Generated by Django 3.2.5 on 2024-04-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetesapp', '0002_auto_20240424_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='mail',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
