# Generated by Django 3.2.5 on 2024-04-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetesapp', '0003_appointments_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='mail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
