# Generated by Django 3.2.5 on 2024-04-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetesapp', '0004_alter_feedback_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='mail',
            field=models.EmailField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
